### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by linakherchi** [xalcolm1/Table-Ouverte#2]
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

**Comment by linakherchi** [comment]
Thanks, Malcolm ! 

1) Why is `owner_id` bigint?
2) Could you please add foreign keys in the details column?
3) Please reference Bluebird to reflect foreign keys that reference other tables. Also make sure that foreign keys and table names are back_ticked
4) Please make changes to reflect the missing checks.

Thank you!

**Comment by xalcolm1** [comment]
bigint is what rails generally defaults to for foreign keys , this is why I did that

**Comment by linakherchi** [comment]
Thanks ! 

Still some updates to go ! Complete those checkmarks so that I can close the issue for you :)

**Comment by xalcolm1** [comment]
can you give more detail on the check marks that are left, I don't understand what is being asked

**Comment by linakherchi** [comment]
Yes - you will need to add back_ticks, which means wrap column tables, table names and foreign keys with `` so that they appear as they are highlighted in grey
