### ISSUE TITLE
Frontend Routes

### ISSUE THREAD

**Issue by linakherchi** [xalcolm1/Table-Ouverte#6]
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

**Comment by linakherchi** [comment]
Need to format routes accordingly (back_ticks)

**Comment by xalcolm1** [comment]
are the components in the correct format?

**Comment by linakherchi** [comment]
Thanks
